# Generated by Django 5.2.14 on 2026-05-31 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('province', models.CharField(default='Manitoba', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('opportunity_type', models.CharField(choices=[('farmers_market', 'Farmers Market'), ('craft_fair', 'Craft Fair'), ('food_festival', 'Food Festival'), ('night_market', 'Night Market'), ('pop_up', 'Pop-Up'), ('holiday_market', 'Holiday Market'), ('exhibition', 'Exhibition'), ('community_event', 'Community Event'), ('retail_opportunity', 'Retail Opportunity'), ('other', 'Other')], max_length=50)),
                ('vendor_categories', models.JSONField(blank=True, default=list)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_date_end', models.DateField(blank=True, null=True)),
                ('event_date_text', models.CharField(blank=True, help_text='Human-readable date description for recurring/complex schedules', max_length=255)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_deadline_text', models.CharField(blank=True, help_text='Human-readable deadline description', max_length=255)),
                ('application_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(max_length=500)),
                ('source_type', models.CharField(choices=[('official', 'Official Website'), ('organizer', 'Organizer Direct'), ('municipal', 'Municipal/Government'), ('social_organizer', 'Social Media (Organizer)'), ('social_repost', 'Social Media (Repost)'), ('community', 'Community Tip')], max_length=30)),
                ('date_found', models.DateField(auto_now_add=True)),
                ('last_checked', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closing_soon', 'Closing Soon'), ('closed', 'Closed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='tentative', max_length=20)),
                ('confidence_score', models.IntegerField(choices=[(1, '1 - Very Low'), (2, '2 - Low'), (3, '3 - Medium'), (4, '4 - High'), (5, '5 - Very High')], default=3)),
                ('vendor_fee', models.CharField(blank=True, max_length=255)),
                ('booth_size', models.CharField(blank=True, max_length=100)),
                ('indoor_outdoor', models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both')], max_length=20)),
                ('power_available', models.BooleanField(blank=True, null=True)),
                ('insurance_required', models.BooleanField(blank=True, null=True)),
                ('food_vendor_notes', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('social_url', models.URLField(blank=True, max_length=500)),
                ('organizer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='opportunities.opportunity')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunities.region')),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ['-confidence_score', 'application_deadline', '-created_at'],
                'indexes': [models.Index(fields=['status', 'confidence_score'], name='idx_status_confidence'), models.Index(fields=['application_deadline'], name='idx_app_deadline'), models.Index(fields=['opportunity_type'], name='idx_opp_type'), models.Index(fields=['city'], name='idx_city'), models.Index(fields=['region'], name='idx_region')],
            },
        ),
    ]
