# Generated by Django 5.2.14 on 2026-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text="List of badge keys, e.g. ['verified', 'vendor_favorite']"),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
