# Generated by Django 5.2.14 on 2026-05-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0002_opportunity_badges_opportunity_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(help_text="A headline quote, e.g. 'My First Market Changed Everything'", max_length=255)),
                ('body', models.TextField()),
                ('photo_url', models.URLField(blank=True, help_text='URL for vendor photo')),
                ('category', models.CharField(choices=[('first_time', 'First Time'), ('success', 'Success Story'), ('tips', 'Tips & Advice'), ('seasonal', 'Seasonal')], default='first_time', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('markets_mentioned', models.ManyToManyField(blank=True, related_name='vendor_stories', to='opportunities.opportunity')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_stories', to='opportunities.region')),
            ],
            options={
                'verbose_name': 'Vendor Story',
                'verbose_name_plural': 'Vendor Stories',
                'ordering': ['-published_date'],
            },
        ),
    ]
