# Generated by Django 5.2.14 on 2026-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('author_name', models.CharField(default='Market Mapper', max_length=200)),
                ('excerpt', models.CharField(help_text='Short summary shown in list views and social sharing.', max_length=300)),
                ('body', models.TextField()),
                ('featured_image_url', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('seasonal_guide', 'Seasonal Guide'), ('market_roundup', 'Market Roundup'), ('vendor_tips', 'Vendor Tips'), ('news', 'News'), ('other', 'Other')], default='other', max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 characters).', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['status', 'published_date'], name='idx_blog_status_pub'), models.Index(fields=['category'], name='idx_blog_category'), models.Index(fields=['slug'], name='idx_blog_slug')],
            },
        ),
    ]
