#!/bin/bash
###############################################################################
# Market Mapper — Full Server Setup Script
# Target: Ubuntu LXC behind Cloudflare Tunnel
#
# Usage: sudo bash setup.sh
###############################################################################
set -euo pipefail

# ── Colors & helpers ────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
step()    { echo -e "\n${CYAN}━━━ $* ━━━${NC}"; }

# ── Preflight checks ───────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "This script must be run as root (use sudo)."

DEPLOY_DIR="/opt/marketmapper"
LOG_DIR="/var/log/marketmapper"
BACKUP_DIR="/opt/marketmapper/backups"
REPO_URL=""  # Set this if cloning from git, or leave empty to copy local

step "1/12 — Updating system packages"
apt-get update -qq
apt-get upgrade -y -qq
success "System updated"

step "2/12 — Installing dependencies"
apt-get install -y -qq \
    python3.11 python3.11-venv python3.11-dev \
    postgresql postgresql-contrib \
    nginx \
    git \
    curl \
    libpq-dev \
    build-essential
success "Dependencies installed"

step "3/12 — Configuring PostgreSQL"
DB_NAME="marketmapper"
DB_USER="marketmapper"
DB_PASS=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(32))")

# Create database user and database
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"

success "PostgreSQL database '${DB_NAME}' and user '${DB_USER}' configured"

step "4/12 — Setting up project directory"
if [[ -d "${DEPLOY_DIR}" ]]; then
    warn "Directory ${DEPLOY_DIR} already exists — updating in place"
else
    if [[ -n "${REPO_URL}" ]]; then
        info "Cloning from ${REPO_URL}..."
        git clone "${REPO_URL}" "${DEPLOY_DIR}"
    else
        SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
        info "Copying project from ${SCRIPT_DIR} to ${DEPLOY_DIR}..."
        mkdir -p "${DEPLOY_DIR}"
        rsync -a --exclude='.venv' --exclude='__pycache__' --exclude='db.sqlite3' \
              --exclude='.git' --exclude='node_modules' \
              "${SCRIPT_DIR}/" "${DEPLOY_DIR}/"
    fi
fi
success "Project files in ${DEPLOY_DIR}"

step "5/12 — Creating Python virtual environment"
if [[ ! -d "${DEPLOY_DIR}/.venv" ]]; then
    python3.11 -m venv "${DEPLOY_DIR}/.venv"
fi
source "${DEPLOY_DIR}/.venv/bin/activate"
pip install --upgrade pip -q
pip install -r "${DEPLOY_DIR}/requirements.txt" -q
deactivate
success "Virtual environment ready"

step "6/12 — Creating .env configuration"
SECRET_KEY=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(50))")

cat > "${DEPLOY_DIR}/.env" << EOF
# Market Mapper Production Configuration
# Generated by setup.sh on $(date -Iseconds)

DJANGO_SETTINGS_MODULE=config.settings.production
SECRET_KEY=${SECRET_KEY}
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@localhost/${DB_NAME}
ALLOWED_HOSTS=marketmapper.ca,www.marketmapper.ca

# Beehiiv Newsletter (configure manually)
BEEHIIV_API_KEY=
BEEHIIV_PUBLICATION_ID=
EOF

chmod 600 "${DEPLOY_DIR}/.env"
success ".env created with generated secrets"

step "7/12 — Running Django migrations"
cd "${DEPLOY_DIR}"
"${DEPLOY_DIR}/.venv/bin/python" manage.py migrate --noinput
success "Database migrations complete"

step "8/12 — Collecting static files"
"${DEPLOY_DIR}/.venv/bin/python" manage.py collectstatic --noinput --clear
success "Static files collected"

step "9/12 — Seeding regions data"
"${DEPLOY_DIR}/.venv/bin/python" manage.py seed_regions || warn "seed_regions command not found or failed — skip if not needed"
success "Region data seeded"

step "10/12 — Creating superuser"
info "Create your admin account:"
"${DEPLOY_DIR}/.venv/bin/python" manage.py createsuperuser || warn "Superuser creation skipped"

step "11/12 — Setting up Nginx"
# Remove default site
rm -f /etc/nginx/sites-enabled/default

# Install Market Mapper config
cp "${DEPLOY_DIR}/deploy/nginx.conf" /etc/nginx/sites-available/marketmapper
ln -sf /etc/nginx/sites-available/marketmapper /etc/nginx/sites-enabled/marketmapper

# Test config
nginx -t || error "Nginx configuration test failed!"
success "Nginx configured"

step "12/12 — Setting up systemd service & permissions"
# Create log directory
mkdir -p "${LOG_DIR}"
mkdir -p "${BACKUP_DIR}"
mkdir -p "${DEPLOY_DIR}/media"

# Set ownership
chown -R www-data:www-data "${DEPLOY_DIR}"
chown -R www-data:www-data "${LOG_DIR}"

# Install and enable systemd service
cp "${DEPLOY_DIR}/deploy/marketmapper.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable marketmapper
systemctl enable nginx

# Start services
systemctl restart nginx
systemctl start marketmapper
success "Services started and enabled"

# ── Done ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  ✅  Market Mapper deployed successfully!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${CYAN}App:${NC}        http://127.0.0.1:8000"
echo -e "  ${CYAN}Logs:${NC}       ${LOG_DIR}/"
echo -e "  ${CYAN}Config:${NC}     ${DEPLOY_DIR}/.env"
echo -e "  ${CYAN}Service:${NC}    systemctl status marketmapper"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "    1. Install cloudflared:  curl -L https://pkg.cloudflare.com/cloudflare-main.gpg | apt-key add -"
echo -e "       echo 'deb https://pkg.cloudflare.com/ jammy main' > /etc/apt/sources.list.d/cloudflare.list"
echo -e "       apt update && apt install cloudflared"
echo -e "    2. Authenticate:         cloudflared tunnel login"
echo -e "    3. Create tunnel:        cloudflared tunnel create marketmapper"
echo -e "    4. Configure tunnel to point to http://localhost:80"
echo -e "    5. Route DNS:            cloudflared tunnel route dns marketmapper marketmapper.ca"
echo -e "    6. Start tunnel:         cloudflared tunnel run marketmapper"
echo -e "    7. Configure BEEHIIV_API_KEY and BEEHIIV_PUBLICATION_ID in .env"
echo -e "    8. Set up backup cron:   crontab -e"
echo -e "       0 3 * * * /opt/marketmapper/deploy/backup.sh"
echo ""
